### ISSUE TITLE
Docs stable version is stuck back at v0.1.3

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#112]
It seems that our docs don't keep all the versions of our releases... See, e.g., here: https://fourierflows.github.io/FourierFlows.jl/stable/

@mortenpi, do you have any insights on this? Is something in our `.travis.yml` or `docs/make.jl` files causing this?

Btw, possibly unrelated, should we remove the cap on `Documenter.jl` v0.19 and use the latest version?

**Comment by mortenpi** [comment]
It seems that [your `DOCUMENTER_KEY` might be corrupted](https://travis-ci.org/FourierFlows/FourierFlows.jl/jobs/474480708#L621-L647)? I would try regenerating the keys. If it is just that then you should be able to just re-run the Travis tag jobs for the missing versions and get the docs.

> Btw, possibly unrelated, should we remove the cap on Documenter.jl v0.19 and use the latest version?

I would try to debug and fix the deployment issue first (not related to Documenter's version), but in general, yes, I would recommend using a newer version.

You need to make quite a few updates to your setup though. First, your should use a [separate build stage for the docs](https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#.travis.yml-Configuration-1). And second, you need to update the various keyword arguments etc. in `make.jl`, for which you can follow the [upgrade instructions for each 0.x minor version in the CHANGELOG](https://github.com/JuliaDocs/Documenter.jl/blob/master/CHANGELOG.md#version-v0200).

**Comment by navidcy** [comment]
thanks @mortenpi. I regenerated the keys. Do things look OK now you think?

**Comment by mortenpi** [comment]
The docs seem to be there now: https://fourierflows.github.io/FourierFlows.jl/v0.3.0/ :slightly_smiling_face: 

Might want to re-trigger this one too to get the 0.2 docs: https://travis-ci.org/FourierFlows/FourierFlows.jl/builds/440992581

Actually, the key regeneration was probably unnecessary -- I didn't notice that your master docs builds have been successful, so simply re-running the build would have been enough. So the key was probably broken at the time when the versions were tagged, but has since been fixed.

**Comment by navidcy** [comment]
Nice.

Regarding removing Documenter v0.2 cap:

**Comment by mortenpi** [comment]
LGTM and the Travis job seems to pass.
