### ISSUE TITLE
Avoid if-else-end in parsevalsum/parsevalsum2

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#239]
Any idea how to overload the `parsevalsum()`/`parsevalsum2()` functions to avoid the if statements, e.g., here:
https://github.com/FourierFlows/FourierFlows.jl/blob/ca332a99b5297c1e9b62a2658ae6e4ce4339abea/src/utils.jl#L110
?

cc @glwagner

**Comment by glwagner** [comment]
To make dispatch possible, information must be encoded via type specification.

Given an array of numbers representing a Fourier transform, there's no way to infer whether uh has the "conjugate symmetric" form or not.

Probably the right way to permit functionality like this is to use a `Field` abstraction (rather than just arrays) for storing data. A well-implemented `Field` abstraction would encode needed metadata with types, such as whether a field is real-valued in physical space.

**Comment by navidcy** [comment]
#FourierFlows v2.0

**Comment by navidcy** [comment]
Also #129

**Comment by navidcy** [comment]
But for now we can write two separate functions, eg `parsevalsum` and `parsevalsumr`.

**Comment by navidcy** [comment]
Since benchmarks in #250 didn't reveal that any benefit was gained, I'm closing this issue.
