### ISSUE TITLE
test_twodturb fails with FilteredTimeSteppers

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#25]
There is a problem with ``test/test_twodturb.jl`` when it uses the Filtered version of the timesteppers. That's why the lines:
https://github.com/FourierFlows/FourierFlows.jl/blob/e8952f05db9d4cb8792c2620ce38c23f8eccc507/test/test_twodturb.jl#L60
https://github.com/FourierFlows/FourierFlows.jl/blob/e8952f05db9d4cb8792c2620ce38c23f8eccc507/test/test_twodturb.jl#L64
are commented out. I spend an afternoon but couldn't figure it out... We need to dig into this.

**Comment by glwagner** [comment]
I think that we shouldn't use the abbreviation "Filtr" to stand for
"Filtered".

The syntax used to initialize FilteredForwardEuler and FilteredETDRK4 isn't
consistent (one is (...g, v); the other is (... eq.LC, g). Should we fix
that? Or is that a bug?

Does it make sense that applying the filter at every time-step changes the
solution more than this test expects? How big is the norm of the
difference? Can the test be rewritten so that the norm of the difference is
printed out when the test fails?

On Wed, Jan 3, 2018 at 6:09 PM, Navid Constantinou <notifications@github.com

**Comment by navidcy** [comment]
We are not enslaved of the test.jl script… We can do, of course, whatever we want and print out whatever we want!

Yes, I would feel more comfortlable if all time-steppers took same arguments.

Is “Filtr” more standard than “Filtered”?  The latter means something, the former only implies it. I don’t have a strong opinion on this issue.

**Comment by navidcy** [comment]
The issue was resolve. I merged #27.
The problem was that the initial condition had spectral power very close to the cutoff wavenumber of the filter. This was resulting in states that were different with more than rel tol 1e-14 after stepforwarding 10 time steps of dt=1e-16 and, thus, the tests were failing.
