### ISSUE TITLE
Add more info about high-wavenumber filtering in `FilteredTimeSTeppers`

### ISSUE THREAD

**Issue by navidcy** [FourierFlows/FourierFlows.jl#352]
We need to include include more information about the exponential filtering. E.g.,

- what the exponentional filtering tries to achieve
- how is the cutoff wavenumber computed
- how is the coefficient exponent computed
- refer to Arbic & Flierl 2003 (or possibly also to LaCasce 1996, Canuto et al. 1988) where this exponential wavenumber filtering originates

cc @liasiegelman

**Comment by liasiegelman** [comment]
Just spotted a minor typo:

https://fourierflows.github.io/FourierFlowsDocumentation/previews/PR353/timestepping/

Given the order p, we calculate the coefficient α so that the *the* filter
value that corresponds to the highest allowed wavenumber in our domain is a
small value, δ, taken to be close to machine precision.

The appears twice in the above sentence (in bold).
